Launcher3: quickstep: TouchInteractionService: Do not crash on boot
When using a 3rd party launcher, registering the recents animation input
consumer on USER_UNLOCKED can fail with:

  java.lang.IllegalStateException: Existing input consumer found with
  name: recents_animation_input_consumer, display: 0, user: UserHandle{0}

which crashes the launcher process. Catch and log the failure instead.

Ported from waterlily-qpr2 258564a46b; the code moved from
TouchInteractionService to TouchInteractionHandler on Android 17.

Change-Id: I11726a95da47c63c777e0d30680260014d14c69a
Signed-off-by: Jis G Jacob <studiokeys@blissroms.org>